server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:bookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

hotel-service:
  url: lb://hotel-service

jwt:
  secret: kJ3984kfj390fkAJsd823kdfkKDJf983ksdflk32kf9sdf8s9dkfjsdlfjskdjfklsjdfkJ3984kfj390fkAJsd823kdfkKDJf983ksdflk32kf9sdf8s9dkfjsdlfjskdjfklsjdf
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
